export const env = {
  NEXT_PUBLIC_SEPOLIA_RPC_URL: process.env.NEXT_PUBLIC_SEPOLIA_RPC_URL,
  NEXT_PUBLIC_CONTRACT_ADDRESS_LOCALHOST:
    process.env.NEXT_PUBLIC_CONTRACT_ADDRESS_LOCALHOST,
  NEXT_PUBLIC_CONTRACT_ADDRESS_SEPOLIA:
    process.env.NEXT_PUBLIC_CONTRACT_ADDRESS_SEPOLIA,
  NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID:
    process.env.NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID,
  NODE_ENV: process.env.NODE_ENV,
};
